{
 "title": "Storj Nodes",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node_id)" } },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storj Nodes Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(storj_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payout Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storj_payout_total_cents{period=\"current\"}) + sum(storj_payout_held_cents{period=\"current\"})) / 100",
     "legendFormat": "Total Payout"
    },
    {
     "expr": "sum(storj_payout_held_cents{period=\"current\"}) / 100",
     "legendFormat": "Held Payout"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(storj_satellite_egress_summary_bytes)",
     "legendFormat": "Total Egress"
    },
    {
     "expr": "sum(storj_satellite_ingress_summary_bytes)",
     "legendFormat": "Total Ingress"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(storj_disk_space_bytes{type=\"used\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_satellite_egress_summary_bytes)",
     "legendFormat": "Egress"
    },
    {
     "expr": "sum(storj_satellite_ingress_summary_bytes)",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "Storage Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_disk_space_bytes{type=\"used\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(storj_disk_space_bytes{type=\"available\"}) - sum(storj_disk_space_bytes{type=\"used\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(storj_disk_space_bytes{type=\"trash\"})",
     "legendFormat": "Trash"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(storj_satellite_egress_summary_bytes[$__rate_interval]))",
     "legendFormat": "Egress Rate"
    },
    {
     "expr": "sum(rate(storj_satellite_ingress_summary_bytes[$__rate_interval]))",
     "legendFormat": "Ingress Rate"
    }
   ]
  },
  {
   "title": "Audits By Satellite",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "  sum by (satellite_id, audit_type) (increase(storj_satellite_audit_status{audit_type=\"online\"}[$__range]))\r\n* on (satellite_id) group_left (satellite_name)\r\n  max by (satellite_id, satellite_name) (storj_satellite_info)",
     "legendFormat": "Online Audits"
    },
    {
     "expr": "  sum by (satellite_id, audit_type) (increase(storj_satellite_audit_status{audit_type=\"total\"}[$__range]))\r\n* on (satellite_id) group_left (satellite_name)\r\n  max by (satellite_id, satellite_name) (storj_satellite_info)",
     "legendFormat": "Total Audits"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(node_id, type) (storj_disk_space_bytes{type=\"available\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node_id, type) (storj_disk_space_bytes{type=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(node_id) (storj_satellite_egress_summary_bytes), \"type\", \"egress_bytes\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(node_id) (storj_satellite_ingress_summary_bytes), \"type\", \"ingress_bytes\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(storj_satellite_online_score) by (node_id), \"type\", \"online_score\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node_id, type) (storj_disk_space_bytes{type=\"trash\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((sum by (node_id) (storj_payout_total_cents{period=\"current\"} + storj_payout_held_cents{period=\"current\"})) / 100, \"type\", \"payout\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((sum by (node_id) (storj_payout_held_cents{period=\"current\"})) / 100, \"type\", \"held_payout\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  label_replace(storj_node_info, \"Value\", \"$1\", \"version\", \"(.*)\"),\r\n  \"type\",\r\n  \"version\",\r\n  \"\",\r\n  \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((sum by (node_id) (storj_last_pinged_timestamp * 1000)), \"type\", \"last_pinged\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((sum by (node_id) (storj_node_up_to_date)), \"type\", \"up_to_date\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used by Satellite",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(storj_satellite_current_storage_used_bytes) by (satellite_id) * on (satellite_id) group_left (satellite_name)\r\n  max by (satellite_id, satellite_name) (storj_satellite_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node ${Node}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "Node" },
  {
   "title": "Payout Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storj_payout_total_cents{period=\"current\", node_id=\"$Node\"}) + sum(storj_payout_held_cents{period=\"current\", node_id=\"$Node\"})) / 100",
     "legendFormat": "Total Payout"
    },
    {
     "expr": "(sum(storj_payout_held_cents{period=\"current\", node_id=\"$Node\"})) / 100",
     "legendFormat": "Held Payout"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(storj_disk_space_bytes{type=\"used\", node_id=\"$Node\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(storj_satellite_egress_summary_bytes{node_id=\"$Node\"})",
     "legendFormat": "Total Egress"
    },
    {
     "expr": "sum(storj_satellite_ingress_summary_bytes{node_id=\"$Node\"})",
     "legendFormat": "Total Ingress"
    }
   ]
  },
  {
   "title": "Network Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_satellite_egress_summary_bytes{node_id=\"$Node\"})",
     "legendFormat": "Egress"
    },
    {
     "expr": "sum(storj_satellite_ingress_summary_bytes{node_id=\"$Node\"})",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "Storage Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_disk_space_bytes{type=\"used\", node_id=\"$Node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(storj_disk_space_bytes{type=\"available\", node_id=\"$Node\"}) - sum(storj_disk_space_bytes{type=\"used\", node_id=\"$Node\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(storj_disk_space_bytes{type=\"trash\", node_id=\"$Node\"})",
     "legendFormat": "Trash"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storj_satellite_egress_summary_bytes{node_id=\"$Node\"}[5m]))",
     "legendFormat": "Egress Rate"
    },
    {
     "expr": "sum(rate(storj_satellite_ingress_summary_bytes{node_id=\"$Node\"}[5m]))",
     "legendFormat": "Ingress Rate"
    }
   ]
  },
  {
   "title": "Audits By Satellite",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "  sum by (satellite_id, audit_type, node_id) (\r\n    increase(\r\n      storj_satellite_audit_status{audit_type=\"online\",node_id=\"$Node\"}[$__range]\r\n    )\r\n  )\r\n* on (satellite_id) group_left (satellite_name)\r\n  max by (satellite_id, satellite_name) (storj_satellite_info)",
     "legendFormat": "Online Audits"
    },
    {
     "expr": "  sum by (satellite_id, audit_type, node_id) (\r\n    increase(\r\n      storj_satellite_audit_status{audit_type=\"total\",node_id=\"$Node\"}[$__range]\r\n    )\r\n  )\r\n* on (satellite_id) group_left (satellite_name)\r\n  max by (satellite_id, satellite_name) (storj_satellite_info)",
     "legendFormat": "Total Audits"
    }
   ]
  }
 ]
}